INCLUDE(${OE_CURRENT_EXTENSION_DIR}/FindSDL.cmake)
INCLUDE(${OE_CURRENT_EXTENSION_DIR}/SetupSDL.cmake)

SET(SDL_MAIN_FOR_MAC "${OE_CURRENT_EXTENSION_DIR}/SDLMain.m")

IF(CMAKE_VERBOSE_MAKEFILE)
MESSAGE("SDL_INCLUDE: ${SDL_INCLUDE_DIR}")
MESSAGE("SDL_LIB: ${SDL_LIBRARY}")
ENDIF(CMAKE_VERBOSE_MAKEFILE)